### ISSUE TITLE
block height exceeded

### ISSUE THREAD

**Issue by KevinHurd** [solsniperr/sol-sniper-bot#4]
We are getting the following error all the time now. Any idea on how to solve this issue?

err: {
      "type": "TransactionExpiredBlockheightExceededError",
      "message": "Signature 2jJFSLTwq4T7VzUZxsb1mQRyHwnobthxtu6NhMV4hvD37bDwR92tNrhR7c71VNaXUrMs5YG7cbGJC9XrMtScEraG has expired: block height exceeded.",
      "stack":
          TransactionExpiredBlockheightExceededError: Signature 2jJFSLTwq4T7VzUZxsb1mQRyHwnobthxtu6NhMV4hvD37bDwR92tNrhR7c71VNaXUrMs5YG7cbGJC9XrMtScEraG has expired: block height exceeded.
              at Connection.confirmTransactionUsingBlockHeightExceedanceStrategy (/home/ec2-user/sol-sniper-bot/node_modules/@solana/web3.js/src/connection.ts:4061:15)
              at processTicksAndRejections (node:internal/process/task_queues:105:5)
              at async Connection.confirmTransaction (/home/ec2-user/sol-sniper-bot/node_modules/@solana/web3.js/src/connection.ts:3872:14)

we have had successful purchases before. We have increased the specification of the server, so there is plenty of resource. Here are the environment variables.

[13:58:37.181] INFO: CONNECTED @ https://rpc.shyft.to?api_key=xxx
[13:58:37.181] INFO: ----------------------------------------------------------
[13:58:37.182] INFO: Wallet Address: xxx
[13:58:37.182] INFO: Snipelist: false
[13:58:37.182] INFO: Mint renounced: false
[13:58:37.182] INFO: Auto sell: true
[13:58:37.182] INFO: T/P: 50%
[13:58:37.182] INFO: S/L: 50%
[13:58:37.187] INFO: Pool size min >: 50.000000000 SOL
[13:58:37.187] INFO: Pool size max <: 999999.000000000 SOL
[13:58:37.187] INFO: Buy amount: 0.010000000 SOL
[13:58:37.345] INFO: -------------------- SEARCH NEW POOLS --------------------

**Comment by KevinHurd** [comment]
sorted
